### ISSUE TITLE
Support Gradle 8.5

### ISSUE THREAD

**Issue by jdneo** [microsoft/build-server-for-gradle#102]
See: 

- https://github.com/microsoft/build-server-for-gradle/blob/a7712845a494de4fdf8f3f8340eb3e639ecf2275/server/src/main/java/com/microsoft/java/bs/core/internal/gradle/Utils.java#L153
- https://docs.gradle.org/8.5-rc-1/userguide/compatibility.html

This should address: https://github.com/microsoft/vscode-gradle/issues/1420#issuecomment-1804781441

**Comment by mozhuanzuojing** [comment]
https://github.com/gradle/gradle/releases/tag/v8.5.0

**Comment by jdneo** [comment]
@mozhuanzuojing Thank you for the reminder.
