### ISSUE TITLE
Build for Java 8

### ISSUE THREAD

**Issue by Arthurm1** [microsoft/build-server-for-gradle#117]
Since Gradle can run on Java 8 and so do some BSP clients, it would be good to build the plugin/server/model for java 8

Currently the project requires Java 17 but I think there are only a few instances of use of java syntax > version 8 and these could be easily changed.

**Comment by jdneo** [comment]
Is it required by Metals?

**Comment by Arthurm1** [comment]
Not required no.  Metals will run on >=8.  But it crops up that some users are still on 8.

Not sure what the oldest version of Gradle is that you want to support but requiring jdk 17 will mean that the min gradle version is 7.3...
https://docs.gradle.org/current/userguide/compatibility.html

Maybe better to leave this issue until someone actually needs it for their project.

**Comment by Arthurm1** [comment]
But looking at Android - it's minimum java version is 11 so 🤷

**Comment by jdneo** [comment]
Ah, I see.

The build server running on java 17 not necessarily means that gradle daemon runs on 17 too.

Client can pass a list of jdk installations during initialization: https://github.com/microsoft/build-server-for-gradle/blob/b77ecfd4163b23a16a01068df111c98d56874044/server/src/main/java/com/microsoft/java/bs/core/internal/model/Preferences.java#L58

And server will pick the matchest jdk for gradle (call `.setJavaHome(xxx)` when using tooling api): https://github.com/microsoft/build-server-for-gradle/blob/b77ecfd4163b23a16a01068df111c98d56874044/server/src/main/java/com/microsoft/java/bs/core/internal/services/LifecycleService.java#L182

**Comment by jdneo** [comment]
No related plans in the short term, close for now.
