### ISSUE TITLE
Enhance Gradle BSP by implementing the BSP requests that are currently unsupported

### ISSUE THREAD

**Issue by Sidhaarthsr** [microsoft/build-server-for-gradle#141]
In order to provide extensive feature support for Gradle Projects, we will enhance the Gradle Build Server by implementing all the necessary BSP requests that are currently unsupported.

BuildTargetRun
BuildTargetTest	
DebugSessionStart
BuildTargetInverseSources

Related Links for more information : 

https://gradle.github.io/community/events/gsoc/2024/gradle-build-server-devx/
https://gitlab.eclipse.org/eclipsefdn/emo-team/gsoc-at-the-ef/-/issues/5

**Comment by jdneo** [comment]
https://github.com/microsoft/build-server-for-gradle/pull/124 covers:

- `buildTarget/jvmTestEnvironment`
- `buildTarget/run`
- `buildTarget/test`

I haven't had a time to review that PR, but that can be a good start.

**Comment by jdneo** [comment]
related issue: https://github.com/microsoft/build-server-for-gradle/issues/119
